name: dbtengine   # Your project name
version: 1.0.0           # Project version

config-version: 2        # Configuration version (2 is the latest)

# Define paths to models, seeds, snapshots, and other components
model-paths: ["models"]      # Directory where your models (.sql files) are located
seed-paths: ["seeds"]        # Directory for raw data seeds
snapshot-paths: ["snapshots"] # Directory for snapshots
analysis-paths: ["analysis"] # Directory for analyses
test-paths: ["tests"]        # Custom tests
macro-paths: ["macros"]      # Directory for macros
docs-paths: ["docs"]         # Directory for documentation markdown files

# Specify where DBT will write compiled SQL and run results
target-path: "target"        # Directory for compiled SQL
clean-targets:
  - "target"
  - "dbt_packages"  # Update to the new default path

# Default database configurations
profile: nba_profile         # Profile defined in profiles.yml for database connection

# Custom settings for model configurations
models:
  +materialized: table        # Default materialization (view, table, incremental, ephemeral)
  staging:
    +schema: staging       # target Schema for staging models

# Define tests and other project-level customizations (optional)
on-run-start:  # SQL or macros to run at the start of a dbt run
  - "CREATE SCHEMA IF NOT EXISTS staging;"

on-run-end:    # SQL or macros to run at the end of a dbt run
  - "{{ log('dbt project completed successfully.', info=True) }}"
